<hr/>
<div class="">
	<div class="">
		<div class="block newsletter">
			<div class="title">
				<strong>Gift Card</strong>
			</div>
			<div class="content">
				<form class="form subscribe" method="post" novalidate="novalidate" action="<?php /* @escapeNotVerified */ echo $block->getUrl('exgiftcard/customer/redeemcoupon') ?>" id="gift-card-reedeem-form">
					<div class="field newsletter">
						<div class="control">
							<label for="newsletter">
								<input name="giftcard" type="text" id="giftcard" placeholder="Enter your gift card code" data-validate="{required:true}">
							</label>
						</div>
					</div>
					<div class="actions">
						<button class="action subscribe primary sr-only" title="Subscribe" type="submit" aria-label="Subscribe">
							<span>Reedem</span>
						</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<script type="text/x-magento-init">
    {
        "#gift-card-reedeem-form": {
            "validation": {}
        }
    }
</script>
